### ISSUE TITLE
Display in transformation state 

### ISSUE THREAD

**Issue by Forcecat01** [L2jOrg/L2jOrg#102]
The transformation is displayed only from the type of the character, other players see the character in its normal state 

As I see 
![Screenshot_4](https://user-images.githubusercontent.com/54755997/113060531-71411500-91b9-11eb-9673-48227fe1e3be.png)

How others see me 
![Screenshot_3](https://user-images.githubusercontent.com/54755997/113060337-2c1ce300-91b9-11eb-989a-65050a20db25.png)

**Comment by vicochips** [comment]
272 protocol ? :O

**Comment by JoeAlisson** [comment]
Which transformation are you using?

I tried 2, both are  working fine

![Shot00001](https://user-images.githubusercontent.com/5034192/113140385-bdfb0f00-91fe-11eb-8f3e-94e0d96c7af6.jpg)

![Shot00000](https://user-images.githubusercontent.com/5034192/113140356-b471a700-91fe-11eb-94f4-1a780eeae468.jpg)

**Comment by Psixxo** [comment]
Chapa transformation scroll

**Comment by Forcecat01** [comment]
Scroll id 99015

Any of these transformations 
\data\stats\transformations
