### ISSUE TITLE
Using Skill for different weapons with auto use

### ISSUE THREAD

**Issue by GPADILHACARDOSO** [L2jOrg/L2jOrg#105]
**Describe the bug**
The characters are able to use weapon restrict skills changing weapon after autouse

**To Reproduce**
1. Learn Power Shot(bow skill)
2. Equip Bow
3. Put Power Shot on Bar and put to autouse
4. Change to other weapon
5. Character will use Power Shot with that weapon

**Expected behavior**
Dont use skills with restrict weapon needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/9576131/113643209-2bbc9600-9658-11eb-98cc-edf808d50e8b.png)
![image](https://user-images.githubusercontent.com/9576131/113643224-370fc180-9658-11eb-9c22-6bfa6880ca27.png)
![image](https://user-images.githubusercontent.com/9576131/113643246-442cb080-9658-11eb-8e12-9c9c763c4218.png)
![image](https://user-images.githubusercontent.com/9576131/113643265-4ee74580-9658-11eb-824e-8535157a20ac.png)

**REV**
Essence 306

**Comment by JoeAlisson** [comment]
Will be addressed in #57

**Comment by JoeAlisson** [comment]
This only happens with GM players, try with player without access level
