### ISSUE TITLE
Erro gameserver

### ISSUE THREAD

**Issue by spiteridiick** [L2jOrg/L2jOrg#123]
O Gameserver Essence-306 está dando esse erro.
![bug](https://user-images.githubusercontent.com/54906606/116802715-70b6d980-aaeb-11eb-9e0e-28e147aa209b.png)

**Comment by matrixane** [comment]
u need put some string into "RatevitalityLost" and "RatevitalityLost"

**Comment by JoeAlisson** [comment]
Fixed in ac8da65
