### ISSUE TITLE
Shine Side mana recovery / use finding souls in shape 

### ISSUE THREAD

**Issue by Forcecat01** [L2jOrg/L2jOrg#126]
`skill id="397" name="Shine Side"`

Has parameter 
```
<stat-modify stat="ABSORB_MANA_DAMAGE_PERCENT">
<power initial="40">
<value level="2">60</value>
</power>
</stat-modify>
```

in the form does not restore MP from damage. 
should restore MP when dealing damage. 
![33](https://user-images.githubusercontent.com/54755997/117053584-d096c580-ad21-11eb-9b70-72739a30c1a6.gif)

the same skills:
during transformation prohibit using 
skill id="393" name="Shine Soul Finding"
skill id="394" name="Shadow Soul Finding"

![34](https://user-images.githubusercontent.com/54755997/117053979-469b2c80-ad22-11eb-8174-a1e88d333020.gif)

**Comment by JoeAlisson** [comment]
There is a chance of 30% to absorb mana in code. Is there this chance in retail?


`if (Rnd.get(10) < 3) // Classic: Static 30% change.
                {
                    absorbPercent = stats.getValue(Stat.ABSORB_MANA_DAMAGE_PERCENT, 0);
                    if (absorbPercent > 0)
                    {
                        int absorbDamage = (int) Math.min((absorbPercent / 100.) * damage, stats.getMaxRecoverableMp() - status.getCurrentMp());
                        absorbDamage = Math.min(absorbDamage, (int) target.getCurrentMp());
                        if (absorbDamage > 0)
                        {
                            setCurrentMp(status.getCurrentMp() + absorbDamage);
                        }
                    }
                }
            }
`

**Comment by Forcecat01** [comment]
the fact is that it should restore MP from the damage done, I set a 99% chance of no changes. it can restore 1 time completely MP. should with every blow (damage) dealt with a chance
