### ISSUE TITLE
Quest items 

### ISSUE THREAD

**Issue by Forcecat01** [L2jOrg/L2jOrg#127]
when a character is in a group, another character in the group kills monsters and you get quest items while in the town

![3323](https://user-images.githubusercontent.com/54755997/117054878-3d5e8f80-ad23-11eb-896f-266f831cb4be.gif)

**Comment by JoeAlisson** [comment]
Is it in a specific quest or all of them?

**Comment by Forcecat01** [comment]
> Is it in a specific quest or all of them?

all initial quests

**Comment by Izonami** [comment]
Looks like problem in this `if (MathUtil.isInsideRadius3D(npc, player, 1200))` should be `if (MathUtil.isInsideRadius3D(npc, partyMember, 1200))` 
and in this line 
`addKillId(ARACHNID_PREDATOR, SKELETON_BOWMAN, RUIN_SPARTOI, RAGING_SPARTOI, RAGING_SPARTOI, TUMRAN_BUGBEAR, TUMRAN_BUGBEAR_WARRIOR); `
remove double RAGING_SPARTOI

**Comment by Bru7aLMike** [comment]
I'm 100% sure that I had this fixed! Someone must have edited the script
afterwards! I remember spending two hours on this particular issue and
fixing it.

На пт, 7.05.2021 г. в 13:41 ч. Izonami ***@***.***> написа:

**Comment by JoeAlisson** [comment]
Is this issue still happening ?
