### ISSUE TITLE
Attribute Spirits

### ISSUE THREAD

**Issue by Forcecat01** [L2jOrg/L2jOrg#130]
https://l2wiki.com/classic/Attribute_System
_The amount of extracted Attribute Fragments depends on the amount of XP gained by the Spirit - the more XP it has at the moment of extraction, the more Attribute Fragments will be extracted._

how can you increase the number of balls when retrieving? as far as I know, at stage 1 of level 10, not 9 balls are extracted, but 19 
`<spirit name="Ignis - Minor Flame Spirit" type="1" stage="1" npc="13566" extract-item="91040" max-characteristics="5">`

After extraction should give level 9 and 0% 
![Screenshot_5](https://user-images.githubusercontent.com/54755997/117057118-c1197b80-ad25-11eb-8cec-8451c8a5f6e8.png)

now gives level 10 and 8.52% and there is no way to extract below 
![Screenshot_6](https://user-images.githubusercontent.com/54755997/117057211-d9899600-ad25-11eb-9139-4f23010e15ab.png)

**Comment by JoeAlisson** [comment]
The experience consume amount was added to elemental-spirits.xml in #154. Now you can define how much elemental experience is needed to each star particle

**Comment by Forcecat92** [comment]
writes a message every time it reaches the maximum value of the attribute. after killing every monster 
![Screenshot_2](https://user-images.githubusercontent.com/54755997/123565461-a3b4db00-d7c5-11eb-8b58-f0c75ea239a0.png)
