### ISSUE TITLE
Rank system

### ISSUE THREAD

**Issue by Psixxo** [L2jOrg/L2jOrg#133]
The rank system should be displayed from 40 lvl and getting the 2nd profession. And now she works from level 76 and getting the 3rd profession. Need fix ^^

**Comment by JoeAlisson** [comment]
The project is based on NA server. Look at the Ranking System section:

https://www.lineage2.com/news/classic-shadow-of-the-kamael-patch-notes

But if you want to change it, you just need to edit these sql:

https://github.com/L2jOrg/L2jOrg/blob/da2342ee9b0671fcb22c075adaac91a912a7427a/Gameserver/src/main/resources/sql/install/1_characters.sql#L100

https://github.com/L2jOrg/L2jOrg/blob/da2342ee9b0671fcb22c075adaac91a912a7427a/Gameserver/src/main/resources/sql/install/1_characters.sql#L130

**Comment by Psixxo** [comment]
Thank you. Clear. Not all sources are verified. For the Russian region, this means that they did it separately from level 40.
