### ISSUE TITLE
items use (character sit)

### ISSUE THREAD

**Issue by Forcecat01** [L2jOrg/L2jOrg#145]
let's say the character is in the combat zone, and it is worth the auto use of items, if the char is sitting, the items are used until it ends,
- sitting there is no ban on use
- spend all the items that are 

![34](https://user-images.githubusercontent.com/54755997/119276046-3c819500-bc21-11eb-818e-819e98199c3b.gif)

**Comment by JoeAlisson** [comment]
Hi, can you check if this was fixed in this branch?
 [bugfixes/use_items_sitting](https://github.com/L2jOrg/L2jOrg/tree/bugfixes/use_items_sitting)

**Comment by Forcecat01** [comment]
> 
> 
> Hi, can you check if this was fixed in this branch?
> [bugfixes/use_items_sitting](https://github.com/L2jOrg/L2jOrg/tree/bugfixes/use_items_sitting)

the item is used while sitting, but once. problem solved. thank you 
![31](https://user-images.githubusercontent.com/54755997/119729188-0b050580-be7d-11eb-8d2e-2add560c3f1f.gif)
