### ISSUE TITLE
Can't target a party member

### ISSUE THREAD

**Issue by Psixxo** [L2jOrg/L2jOrg#150]
Can't target a party member if you are in different locations.
From this it is concluded, how is the summon a party member?

**Comment by JoeAlisson** [comment]
It's working fine to me. How did you tried it ? 

![Shot00002](https://user-images.githubusercontent.com/5034192/122670579-31c30d00-d199-11eb-98f2-9dea4f9f391f.jpg)

**Comment by Forcecat92** [comment]
works good. 
![11](https://user-images.githubusercontent.com/54755997/123526243-2d3dad80-d6df-11eb-8da4-b57ef93e5682.gif)
