### ISSUE TITLE
No success sound Dagger Blow Skills

### ISSUE THREAD

**Issue by UchihaSV** [L2jOrg/L2jOrg#16]
In Retail Dagger Blow skills have sound like Critical Hit when success, proof video:
https://www.youtube.com/watch?v=wT0XyENh3Vg

P.S.: Need implementation playing sound around target, when blow success with depending sound volume from distance, not just PlaySound Broadcast, which playing sound 100% volume in any range.

**Comment by JoeAlisson** [comment]
The skill's sound is working fine here
