### ISSUE TITLE
Herbs not works

### ISSUE THREAD

**Issue by Cz3s1ek** [L2jOrg/L2jOrg#165]
When pick up herbs is no effect on chars, for example event Cheaf Monkey Event when mobs drop Bunch Banana after pick up item don't giwe buff.

**Comment by Forcecat92** [comment]
if auto-loot items are enabled, a bunch of bananas is assigned, but does not give any effect.
if you turn off autoloot, bunches of bananas fall to the ground but writes **"Incorrect item count"** and does not give any effect 

![Screenshot_4](https://user-images.githubusercontent.com/54755997/124129501-81051980-da86-11eb-9adc-28f3d4041dd8.png)

**Comment by Forcecat92** [comment]
![11](https://user-images.githubusercontent.com/54755997/124190268-a287f480-daca-11eb-8cd9-0db05cfd2a05.gif)


if you enable items autopickup, no buff is assigned after killing monsters. only if you pick the herb off the floor 
![Screenshot_4](https://user-images.githubusercontent.com/54755997/124191004-d0216d80-dacb-11eb-8218-8b1912e4bd12.png)

**Comment by Cz3s1ek** [comment]
Still same, no works herbs, is no diference betwen normal drop items and herb items, on config when is disabled autoloot, herbs drop on ground and when pick up is works perfectly, but when that option is enabled and auto loot is works, all items go to strait to inventory, but herbs not works, shows on message you get herb but no effect, other way is cant divide herbs from normal items on drop.
