### ISSUE TITLE
Talisman Of Fate Upgrade

### ISSUE THREAD

**Issue by Cz3s1ek** [L2jOrg/L2jOrg#172]
When try to upgrade Talisman of Fate id-70294 is not work, on log show error:
[1;31m[ERROR][2021-07-03 14:05:22][29][ClientPacket:run:55]: [[272] [Classic - Kamael [Dawn of Heroes]]: 1.7.0-RC1-c9db32a (2021-07-02T11:39:26.128+0100)] Error while running packet org.l2j.gameserver.network.clientpackets.MultiSellChoose@4876062b from client [Player: Player:Cz3s1ek[41251] - Account: admin - IP: 86.185.232.94]: null
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at org.l2j.gameserver/org.l2j.gameserver.model.ItemInfo.<init>(ItemInfo.java:58)
	at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.AbstractInventoryUpdate.addItem(AbstractInventoryUpdate.java:58)
	at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.MultiSellChoose.consumeIngredients(MultiSellChoose.java:266)
	at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.MultiSellChoose.runImpl(MultiSellChoose.java:148)
	at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:53)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
	at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$PriorityThread.run(PriorityThreadFactory.java:58)
But when is multisell edit from:
`<ingredient` id="70294" count="2"/> <!-- Receivable: Talisman of Fate Lv. 1 `-->`
to
`<ingredient` id="70294" /> <!-- Receivable: Talisman of Fate Lv. 1 `-->`
`` <ingredient id="70294" /> <!-- Receivable: Talisman of Fate Lv. 1 `-->`

is working well.

**Comment by therealnevax** [comment]
There is another id that has to go with it. You also may have to unlock the ability for your region under the combinationitems.dat

**Comment by Forcecat92** [comment]
CombinationItemData_Classic.dat 
![Screenshot_4](https://user-images.githubusercontent.com/54755997/124398651-8a5ce300-dd1f-11eb-9fd5-57868fd81328.png)

if you want to combine any items, use  applycountry={-1} for all items

[CombinationItemData_Classic.zip](https://github.com/L2jOrg/L2jOrg/files/6760545/CombinationItemData_Classic.zip)
take my file if you need it and try with it. just replace in the systems folder

**Comment by Cz3s1ek** [comment]
Thanks a lot, but this talisman is upgrade on npc in Giran "Veruti", so this operation is made on multisell 4117.xml, and when is use 
function "count" is that happen this error, but when is add separate two items to upgrade one higher is working well and is retail like i check on ncsoft server and is looks like I make change :) so need use my 4117.xml to correct works :)

`<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://l2j.org"
      xsi:schemaLocation="http://l2j.org multisell.xsd"
      chance-based="true">
    
    <npcs>
        33977 
    </npcs>
    <item>
        <ingredient id="70294" /> 
        <ingredient id="70294" /> 
        <production id="70295"/> 
        <production id="70295" chance="50"/> 
        <production id="70294" chance="50"/> 
    </item>

    <item>
        <ingredient id="70294"/> 
        <ingredient id="71818"/> 
        <production id="70295"/> 
        <production id="70295" chance="50"/> 
        <production id="70294" chance="50"/> 
    </item>

    <item>
        <ingredient id="70295" /> 
        <ingredient id="70295" /> 
        <production id="70296"/> 
        <production id="70296" chance="40"/> 
        <production id="70295" chance="60"/> 
    </item>

    <item>
        <ingredient id="70296" /> 
        <ingredient id="70296" /> 
        <production id="70297"/> 
        <production id="70297" chance="20"/> 
        <production id="70296" chance="80"/> 
    </item>

    <item>
        <ingredient id="70297" /> 
        <ingredient id="70297" /> 
        <production id="70298"/> 
        <production id="70298" chance="10"/> 
        <production id="70297" chance="90"/> 
    </item>
</list>`

printscrin from official:

![Shot00000](https://user-images.githubusercontent.com/46694913/124453012-dab75d80-dd7e-11eb-88bc-2bff57236055.jpg)

and from my server:

![Shot00068](https://user-images.githubusercontent.com/46694913/124453182-063a4800-dd7f-11eb-8e22-b7e82c207503.jpg)

**Comment by Forcecat92** [comment]
The same item ID simply displays it in the sales list, for the chance of getting it, it does not seem to stick

Can be made up to the last level and upgraded to an improved golden talisman

**Comment by Cz3s1ek** [comment]
maybe you have right , i dont'know, but with oryginall xml not works and gige error, and looks diferent becouse on required items shows only one picture and shows many items you have on inventory and when you try exchange effect is null and error on log, when you use my xml is works perfect, dont know maybe is diferent id of all talismans start from 49727, with this is also works, and is skill add to item, to id 70294 need add skill just and works same :)
