### ISSUE TITLE
All Quests for Adena with hunting not works

### ISSUE THREAD

**Issue by Cz3s1ek** [L2jOrg/L2jOrg#175]
I check quests for adena and not works properly.
When you take quest and go to hunt, quest items is grow up, 
but when you need get any reward, is no chance, quest items disapire but no adena reward,
is looks like script dont check quest items on player inventory.

**Comment by therealnevax** [comment]
Well I know kill quests work, what level and what quest are you looking at exactly, example needed so I can test with you to see if everyone is experiencing this issue.

**Comment by Cz3s1ek** [comment]
Acctualy all, but Joe make fix now, so i test and with ths fix on gameserver all works fine now :)
