### ISSUE TITLE
Wrong cursor marker on click to Players

### ISSUE THREAD

**Issue by UchihaSV** [L2jOrg/L2jOrg#18]
When u target any player, then click to player to follow him, u can see sword cursor marker(like attack state) or chat dialog cursor marker(like when click on NPC).

**Comment by vicochips** [comment]
I just try on retail, it should be the chatdialog cursor by default when clicking on a char.

**Comment by UchihaSV** [comment]
Ok, but sometimes i can see sword cursor on player without CTRL pressing, when clicking.

**Comment by TokTil-Dev** [comment]
@UchihaSV whats protocol this bug on
