### ISSUE TITLE
Light Elves dont exist in 311.

### ISSUE THREAD

**Issue by therealnevax** [L2jOrg/L2jOrg#190]
What I mean by this is that they don't show up what-so-ever, even to GM.
![image](https://user-images.githubusercontent.com/74559391/126907107-67bf9c7f-fc45-4010-b875-45b53925e2dc.png)
As you can see, from the Light Elf point of view, you can see everyone.
![image](https://user-images.githubusercontent.com/74559391/126907117-9c1c4a16-8367-4d45-a30e-d61ad558dafe.png)
I believe this is from the GM Point of view
![image](https://user-images.githubusercontent.com/74559391/126907133-0e6c11b9-2681-47ff-bf5f-6619c8593abb.png)
This one is from the Orc's point of view.
![image](https://user-images.githubusercontent.com/74559391/126907156-8582e6f8-0400-4d5f-a66e-41184ff76636.png)
This is from the Dark Elf Point of view.
![image](https://user-images.githubusercontent.com/74559391/126907170-c873a52f-7792-4e8b-8539-fd9d044bc965.png)
This is from a different Light Elf Point of view to show that even the Light Elves can't see each other.

I don't know how to fix this or else I would. I am assuming a packet issue, but I am unsure.

**Comment by vicochips** [comment]
fixed
