### ISSUE TITLE
Fishing not work

### ISSUE THREAD

**Issue by Cz3s1ek** [L2jOrg/L2jOrg#201]
char is equipped with rod and baits, zone for fishing is shows to start fishing but no action, dont start fishing.

**Comment by JoeAlisson** [comment]
It is working fine here, where did you try it ?

![output](https://user-images.githubusercontent.com/5034192/127637553-e429eb6a-bc81-44e7-9320-41a71e52bf44.gif)

**Comment by Cz3s1ek** [comment]
hum, on all places where shows fishing icon, so is mean i some miss from some updates :), can you told me what skills on xml is reqire to working fine ?

**Comment by Cz3s1ek** [comment]
hum, is looks i move all updated files, i compile clear core and still same, will create completle clear server from 0 to check, becouse i miss some i think :)

**Comment by Cz3s1ek** [comment]
Yes is some not well, i search where, on data pack or on core :)

**Comment by Cz3s1ek** [comment]
Ok is problem on datapack, i need to discover what i miss, i think some of file is out of date :)

**Comment by Cz3s1ek** [comment]
Ok is not files, is geodata, so fishing not works with enabled geodata.
