### ISSUE TITLE
Silence not interrupt cast skill bug

### ISSUE THREAD

**Issue by UchihaSV** [L2jOrg/L2jOrg#22]
When monster casting some magic skill and u put him in Silence effect - it's not interrupt casting skill, mob can finish cast, under abnormal.

**Comment by vicochips** [comment]
Did u try with the skill silence, or another one ?

**Comment by UchihaSV** [comment]
Yes, Silence.

**Comment by vicochips** [comment]
Fixed

**Comment by JoeAlisson** [comment]
> Fixed

Confirmed
