### ISSUE TITLE
All server types - Daily Rewards (attendance rewards) reset.

### ISSUE THREAD

**Issue by therealnevax** [L2jOrg/L2jOrg#221]
From what I've experienced if you close the server after a fresh build and install that build and start up your server again, it refreshes the daily rewards (attendance rewards) so that you can obtain daily rewards multiple times. I feel this would pose a problem when anyone launches a live server and has to take the server down mid-day for whatever reason before a server restart. It would allow people to claim daily rewards (attendance rewards) more than once a day.

**Comment by JoeAlisson** [comment]
How did you shutdown it ? 

It seems you killed the process, so the server didn't had the "chance" to save the data. You need to shutdown through admin cmd, using the shutdown task or terminating the process.

The server uses a shutdown hook to save the data. So you need to give a chance to the server executes this hook, if you kill the process, there is a high probability to occurs  data loss.

**Comment by therealnevax** [comment]
I'll try that going forward. I never shutdown the server within the actual game. I always closed the game and shut down the server manually by just closing. After what you just told me, im sure it'll fix the problem.
