### ISSUE TITLE
Melee range attacking bug

### ISSUE THREAD

**Issue by UchihaSV** [L2jOrg/L2jOrg#24]
Character can run around a target when try an attack in melee range:
You and the monster just run through each other and then turn around to attacking, instead of stopping at close range in front and attack target. In some cases you(with monster) can enter in loop and run around each other endlessly, without attacks.

**Comment by vicochips** [comment]
It seems that we have finally found the problem. Commit soon, to test

**Comment by JoeAlisson** [comment]
I couldn't reproduce it anymore
