### ISSUE TITLE
Clan Reputation

### ISSUE THREAD

**Issue by Cz3s1ek** [L2jOrg/L2jOrg#259]
When Clan member make lvl up, clan reputation is not added .

**Comment by Psixxo** [comment]
What protocol?

**Comment by Cz3s1ek** [comment]
Classc 272

**Comment by JoeAlisson** [comment]
It is working fine here, can you describe in details ? 
what is the clan level ?
what is the player level ?

**Comment by Cz3s1ek** [comment]
clan lvl 2
players lvls from begain to 64, and on character table i have clan id, but on clan_data is only clan id, leader id, max online, hunting points and previus hunting points,
on table clan_members none, all table is empty.

**Comment by Cz3s1ek** [comment]
manually add reputation for clan from admin panell have non effect

**Comment by Cz3s1ek** [comment]
used command //setreputation xxx no effect

**Comment by Cz3s1ek** [comment]
I install fresh and clean test server, and clan points not works, manualy add reputation to clan not works, and after last update stop works function on admin shift-click on char to open information window.

**Comment by Cz3s1ek** [comment]
Ok, so i found information is all ok, when clan rich lvl 5 reputation will grow up with lvl up each clan member, so all is correct.
