### ISSUE TITLE
Looped items / skills are reset on the skill bar

### ISSUE THREAD

**Issue by Psixxo** [L2jOrg/L2jOrg#28]
After learning the skills, the looped items / skills are reset to the skill bar.

**Comment by Forcecat01** [comment]
Here's how it works. 

![3](https://user-images.githubusercontent.com/54755997/110256087-04ff3700-7fa8-11eb-9636-4cd3833dca07.gif)

**Comment by vicochips** [comment]
We have fixed it :O, it is still not working ?

**Comment by Forcecat01** [comment]
> 
> 
> We have fixed it :O, it is still not working ?

no, same problems
