### ISSUE TITLE
Blue gem

### ISSUE THREAD

**Issue by Psixxo** [L2jOrg/L2jOrg#30]
Blue gem when creating an enchant, until you talk to an assistant, blue gem does not drop from gremlins

**Comment by UchihaSV** [comment]
I tried create a dwarf(as second char in account) and blue gem doesn't drop, even after talk with newbie helper.

**Comment by Forcecat01** [comment]
> I tried create a dwarf(as second char in account) and blue gem doesn't drop, even after talk with newbie helper.

yeah, that's the problem until you talk to the assistant. the gem won't fall
