### ISSUE TITLE
Spoiled mobs after death no visual effect

### ISSUE THREAD

**Issue by UchihaSV** [L2jOrg/L2jOrg#36]
When u use success spoil on mobs and kill them, after death they no any visual effect.

In retail spoiled effect should be like a small fireworks above the body:
![изображение_2021-03-03_160701](https://user-images.githubusercontent.com/10499249/109767335-bdd91500-7c3a-11eb-9a80-503705e335b5.png)

**Comment by MaJr-Dp** [comment]
Линк дай, откуда ты взял эту инфу

**Comment by UchihaSV** [comment]
> Линк дай, откуда ты взял эту инфу

It's from Patchnotes Classic 1.5 -> https://4gameforum.com/threads/532203/

**Comment by MaJr-Dp** [comment]
Patchnotes Classic 1.5 - old information

**Comment by UchihaSV** [comment]
> Patchnotes Classic 1.5 - old information

Yes, they did it a very long time ago and did not seem to change it, but here you have no any effect for spoil.

**Comment by LeonanCarvalho** [comment]
> > Линк дай, откуда ты взял эту инфу
> 
> It's from Patchnotes Classic 1.5: https://4gameforum.com/threads/532203/
> 
> `The visual effect of the "Spoil" skill, which appears after the death of a monster, has been changed: now, in addition to a blue glow, a bright fireworks display will be visible over the corpse of the monster. `

And remains until 286 as far I know, unless it changed in the 306 protocol
