### ISSUE TITLE
physical skills, no penalty, gaining experience/drop/ from monsters 

### ISSUE THREAD

**Issue by Forcecat01** [L2jOrg/L2jOrg#78]
already talked about it, but I'd rather duplicate it here.

Physical skills do not have a penalty and inflict damage to monasters of any level.. I always hit monsters with physical skills, with magicians it is completely different, 43 magician does not when he does not hit a monster above level 11+. 

![rangeattack](https://user-images.githubusercontent.com/54755997/110336978-75ed3000-8036-11eb-8fde-478d2af89016.gif)

![rangeattack2](https://user-images.githubusercontent.com/54755997/110336986-77b6f380-8036-11eb-8c20-3f28703ad7e3.gif)

> With an increase in the difference between the levels of the character and the monster, the number of trophies, adena and experience dropped out decreases, and with a very large difference in levels (11 or more), trophies, experience and adena cease to drop out at all. Therefore, with an increase in the level of the character, it is necessary to look for monsters that are suitable for the level. 

- Formula used to determine damage dealt to monsters of level 78 and above:
1. The amount of damage done to monsters is reduced if your level is 2 or more below the level of the monster.
2. Damage is not reduced if the character is of the same level with the monster or higher.
3. The damage done by a servant or pet will depend on the level of the owner, not on the level of the servant / pet.
4. Damage reduced for all types of attacks (weapons, skills, etc.)
5. This change does not apply to PvP.

- Magic Resistance Formula for Monsters 78 and above:
1. If the attacker's level is 3 or more below the monster's level, the chance that the monster will successfully resist magic damage increases.
2. Changed the method for determining the resistance of monsters to magic attacks
3. Monsters' chance to deflect magic damage is now based on character level, rather than stats or equipment
4. This change does not apply to PvP. 

`Monster name color depending on the level difference `  

![Screenshot_3](https://user-images.githubusercontent.com/54755997/110335535-07f43900-8035-11eb-8e84-4781efff980a.png)

> The color of the monster's name will be displayed in a specific color depending on the difference in the level of the character and the monster. Those. if, for example, the name of the target monster is written in red, it means its level is 11 or more levels higher than the character's level and it is deadly to attack such a monster. 

Level difference between player and monster | Experience gain | Penalty for trophies and adena received
-- | -- | --
+11 | no penalty | no penalty
+10 | no penalty| no penalty
+9 | no penalty| no penalty
+8 | no penalty| no penalty
+7 | no penalty| no penalty
+6 | no penalty| no penalty
+5 | no penalty| no penalty
+4 | no penalty| no penalty
+3 | no penalty| no penalty
+2 | no penalty| no penalty
+1 | no penalty| no penalty
0 | no penalty| no penalty
-1 | no penalty| no penalty
-2 | no penalty| no penalty
-3 | no penalty| small fine 
-4 | no penalty| small fine 
-5 | no penalty| small fine 
-6 | small fine  | severe fine 
-7 | small fine  | severe fine 
-8 | severe fine  | severe fine 
-9 | severe fine  | severe fine 
-10 | severe fine  | severe fine 
-11 | do not gain experience | do not get trophies

killing a level 40 monster, level 85 character, get items and adena, including L coins 

![33](https://user-images.githubusercontent.com/54755997/110339750-8e127e80-8039-11eb-8904-1f2fde491ec4.gif)

**Comment by vicochips** [comment]
I will check on code too if there might be something missing for physical skills

**Comment by Forcecat01** [comment]
> 
> 
> I will check on code too if there might be something missing for physical skills

but with magic skills - everything is in order. and physical skills are not when they are not missed. please see, this mechanic has been tormented for a long time

**Comment by vicochips** [comment]
yes I see it, I will add it on code

**Comment by vicochips** [comment]
For drop items this is config, I just tried, it works :

```
# The min and max level difference used for level gap calculation
# this is only for how many levels higher the player is than the monster
# Default: 8
DropAdenaMinLevelDifference = 10
# Default: 15
DropAdenaMaxLevelDifference = 10

# This is the minimum level gap chance meaning for 10 that the monster will have 10% chance
# to allow dropping the item if level difference is bigger than DropAdenaMaxLevelDifference
# Note: This value is scalling from 100 to the specified value for DropAdenaMinLevelDifference to DropAdenaMaxLevelDifference limits
# Default: 10
DropAdenaMinLevelGapChance = 10

# The min and max level difference used for level gap calculation
# this is only for how many levels higher the player is than the monster
# Default: 5
DropItemMinLevelDifference = 10
# Default: 10
DropItemMaxLevelDifference = 10

# This is the minimum level gap chance meaning for 10 that the monster will have 10% chance
# to allow dropping the item if level difference is bigger than DropAdenaMaxLevelDifference
# Note: This value is scalling from 100 to the specified value for DropAdenaMinLevelDifference to DropAdenaMaxLevelDifference limits
# Default: 10
DropItemMinLevelGapChance = 0
```

**Comment by vicochips** [comment]
For physical damages, I did some code, soon pushed
