### ISSUE TITLE
Monsters ignore ranged attacks 

### ISSUE THREAD

**Issue by Forcecat01** [L2jOrg/L2jOrg#79]
Perhaps I did not pay attention, but before the monsters ran after me, if I attacked from afar, now they just stand and receive damage. 

![444](https://user-images.githubusercontent.com/54755997/110347069-498ae100-8041-11eb-92fb-4a005e12fcda.gif)

![333](https://user-images.githubusercontent.com/54755997/110347073-4b54a480-8041-11eb-97aa-a442ccc18147.gif)

If you come to a distance of + -80, the monster runs after you, but you just have to move away from him (run away) stands again in place and you can beat him from afar 

do not react to anything, you only need to come close for the monster to attack 
![455](https://user-images.githubusercontent.com/54755997/110361699-6cbd8c80-8051-11eb-8280-08a5dfea366e.gif)
![2](https://user-images.githubusercontent.com/54755997/110362147-fa997780-8051-11eb-83ed-ba4db738deff.gif)

endless reclining
![1](https://user-images.githubusercontent.com/54755997/110362152-fb320e00-8051-11eb-8dbd-daefc9e8c5e1.gif)

**Comment by vicochips** [comment]
OK I see the problem, will be fixed soon

**Comment by Forcecat01** [comment]
> 
> 
> Did u try while being invul ?

Yes, it's the same without invulnerability.

here is a typical character. 

![2](https://user-images.githubusercontent.com/54755997/110622675-d2725b80-81ac-11eb-8470-fdbe0e0d3cbb.gif)

![1](https://user-images.githubusercontent.com/54755997/110622683-d3a38880-81ac-11eb-92ad-a1266521951b.gif)

this happened after the updates on March 7, before that I put the kernel and everything is in order, the monsters attack as needed .. please look very critical
