### ISSUE TITLE
Clan Leader Change

### ISSUE THREAD

**Issue by Psixxo** [L2jOrg/L2jOrg#83]
Clan leader change does not work. The relog did not help. Server restart did not help.
![3](https://user-images.githubusercontent.com/68906788/110857594-18711180-82ca-11eb-9209-84e5d39ef370.jpg)

**Comment by Psixxo** [comment]
Tried to change clan leader to "BD"

**Comment by LeonanCarvalho** [comment]
The clan leader is set daily by this method:

https://github.com/L2jOrg/L2jOrg/blob/c3a70c148d07e21dfe5afa26d1aac3db63a9ad03/Gameserver/src/main/org.l2j.gameserver/org/l2j/gameserver/instancemanager/DailyTaskManager.java#L139

After request the clan leader change please check if at table "clan_data" the field "new_leader_id" is set with "BD" id, probably yes.

The clan leader should be changed when the DailyTask run again.
