### ISSUE TITLE
Party exp depends of party member amount implemented?

### ISSUE THREAD

**Issue by UchihaSV** [L2jOrg/L2jOrg#87]
In config Rates i see only party exp, without depends of party member amount.

This is not implemented?
![24537740348_4869c3dd51_o](https://user-images.githubusercontent.com/10499249/111070920-32536400-8517-11eb-942c-76856e9a36a9.png)

**Comment by Psixxo** [comment]
https://l2wiki.com/classic/Party

**Comment by Forcecat01** [comment]
Class combination. Party hunting allows every character to be most useful as everyone has their own role.
    Party chat. While a party exists, its members can use party chat. Party chat text can be seen by every party member in any part of the map. For party chat, use the # prefix.
    XP bonus. The more people in a party, the more XP bonus:

Amount ofpartymembers | XPmultiplier
-- | --
2 | х1.6
3 | х1.65
4 | х1.7
5 | х1.8
6 | х1.9
7 | х2.0
8 | х2.1
9 | х2.2

XP penalty. There more the level difference between party members, the less XP gained by character whose level is lower.


Difference in lvls | Gained XP
-- | --
1 | ~98%
2 | ~95%
3 | ~93%
4 | ~91%
5 | ~88%
6 | ~86%
7 | ~83%
8 | ~81%
9 | ~78%
10 | ~23%
11 | ~22%
12 | ~21%
13 | ~20%
14 | ~19%
15 and more | 0%

**Comment by JoeAlisson** [comment]
Yes, it is implemented. You can find the config in party.properties
