### ISSUE TITLE
Auto Hunt

### ISSUE THREAD

**Issue by GPADILHACARDOSO** [L2jOrg/L2jOrg#95]
Describe the bug
If u put one auto hunt to use example: Power Strike, when skill are in CD the character keep waiting for start hunt new mob

To Reproduce

Up a Human Fighter
Learn Power Strike and put on bar
Turn on Auto Hunt
Kill low lvl mobs with 1 hit
Until Power Strike CD comple the char will stay waiting.

Expected behavior
Auto Hunt for fighter(melee characters only) when skills are in CD need trigger //attack even if //attack on bar are off. The system automatc put the character to attack when do not have skills to use at time.
(Font: Lineage 2 Classic NA, Lineage 2 Essence EU both have same behavior)

**Comment by JoeAlisson** [comment]
Will be addressed in  #57
